name: Check for duplicates or errors

on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - master

jobs:
  checker:
    name: Check for duplicates or errors
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Checking
        run: python3 verify.py
